### ISSUE TITLE
How do I run it?

### ISSUE THREAD

**Issue by yoavst** [NightRa/Mashov-Notificator#1]
just import it to idea?

**Comment by NightRa** [comment]
Currently, there's no main menu and no auto updating, only showing your events.
If you want to run it as is, you should fill the fields in nightra.mashovNotificator.gui.GUIMain.scala, and run it. (idea or sbt)

**Comment by yoavst** [comment]
can you create a runnable jar?

**Comment by NightRa** [comment]
@yoavst Maybe in the following weeks if I'll get the time to.

**Comment by yoavst** [comment]
If you have time, can you create a document for the mashov's api? they removed it from json.asmx :(

**Comment by NightRa** [comment]
@yoavst Oh darn, I haven't gotten the messages API in yet.

**Comment by NightRa** [comment]
@yoavst The API should be very easy to understand from the network.requests package

**Comment by yoavst** [comment]
Unfortunately I'm not scala nor soap developer :(
I'll try to take a look.

**Comment by yoavst** [comment]
@NightRa can you please write the whole login request here? So it will be easier for me to understand.

**Comment by NightRa** [comment]
@yoavst The Login request is a bit complicated; You need to request the currect Ticks state, which depends on time, and combine it to a key using ticks and credentials, with which you can login, and the login gives you a seesion key, with which you can make further requests

**Comment by NightRa** [comment]
@yoavst Also there is a timeout and appropriate computed ajustments for the ticks, but I did not include it here, so I would need to request a new ticks response after my login times out.

**Comment by yoavst** [comment]
so looks like I'll give up on creating a better Mashov app :(

**Comment by NightRa** [comment]
@yoavst Do you have skype? We can talk about it.
Mine is ilan3580.

**Comment by yoavst** [comment]
sent a request, please answer.

**Comment by NightRa** [comment]
@yoavst I didn't get it

**Comment by yoavst** [comment]
:(
Then please send a request to yoavst@hotmail.com

**Comment by yoavst** [comment]
```
Accept: */*
Accept-Encoding: gzip, deflate
Content-Length: 472
Content-Type: text/xml
Soapaction: http://tempuri.org/Login
User-Agent: runscope/0.1

<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
<soap:Body>
<Login>
<id>315144345</id>
<pass>PASSWORD</pass>
<CurrentYearS>5402032015</CurrentYearS>
<ver>202</ver>
<comp>android_id</comp>
<Code>87-4B-D3-81-D4-D7-10-61-53-DA-90-9C-56-C7-07-84-70-CD-39-F6</Code>
</Login>
</soap:Body>
</soap:Envelope>
```

returns:

```
Cache-Control: private
Content-Length: 649
Content-Type: text/xml; charset=utf-8
Date: Tue, 06 Jan 2015 17:29:06 GMT
Server: Microsoft-IIS/7.5
X-Aspnet-Version: 4.0.30319
X-Powered-By: ASP.NET

<?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><soap:Body><soap:Fault><faultcode>soap:Server</faultcode><faultstring>System.Web.Services.Protocols.SoapException: Server was unable to process request. ---&gt; System.NullReferenceException: Object reference not set to an instance of an object.
   at achvaDal.isStudent(String id)
   at achvaDal.UserType(String id, String instDb)
   --- End of inner exception stack trace ---</faultstring><detail /></soap:Fault></soap:Body></soap:Envelope>
```
